//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClientApplication.ServiceReference4 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference4.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetData", ReplyAction="http://tempuri.org/IService1/GetDataResponse")]
        string GetData(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetData", ReplyAction="http://tempuri.org/IService1/GetDataResponse")]
        System.Threading.Tasks.Task<string> GetDataAsync(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IService1/GetDataUsingDataContractResponse")]
        RetailApplication.CompositeType GetDataUsingDataContract(RetailApplication.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IService1/GetDataUsingDataContractResponse")]
        System.Threading.Tasks.Task<RetailApplication.CompositeType> GetDataUsingDataContractAsync(RetailApplication.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetBookByTitle", ReplyAction="http://tempuri.org/IService1/GetBookByTitleResponse")]
        RetailApplication.Books[] GetBookByTitle(string value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetBookByTitle", ReplyAction="http://tempuri.org/IService1/GetBookByTitleResponse")]
        System.Threading.Tasks.Task<RetailApplication.Books[]> GetBookByTitleAsync(string value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetBookByAuthor", ReplyAction="http://tempuri.org/IService1/GetBookByAuthorResponse")]
        RetailApplication.Books[] GetBookByAuthor(string value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetBookByAuthor", ReplyAction="http://tempuri.org/IService1/GetBookByAuthorResponse")]
        System.Threading.Tasks.Task<RetailApplication.Books[]> GetBookByAuthorAsync(string value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetBookByKeyword", ReplyAction="http://tempuri.org/IService1/GetBookByKeywordResponse")]
        RetailApplication.Books[] GetBookByKeyword(string value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetBookByKeyword", ReplyAction="http://tempuri.org/IService1/GetBookByKeywordResponse")]
        System.Threading.Tasks.Task<RetailApplication.Books[]> GetBookByKeywordAsync(string value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddBook", ReplyAction="http://tempuri.org/IService1/AddBookResponse")]
        bool AddBook(int id, string bookTitle, string bookAuthor, string publication, int year, string code, string bookKeyword);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddBook", ReplyAction="http://tempuri.org/IService1/AddBookResponse")]
        System.Threading.Tasks.Task<bool> AddBookAsync(int id, string bookTitle, string bookAuthor, string publication, int year, string code, string bookKeyword);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteBook", ReplyAction="http://tempuri.org/IService1/DeleteBookResponse")]
        bool DeleteBook(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteBook", ReplyAction="http://tempuri.org/IService1/DeleteBookResponse")]
        System.Threading.Tasks.Task<bool> DeleteBookAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetLoginStatus", ReplyAction="http://tempuri.org/IService1/GetLoginStatusResponse")]
        bool GetLoginStatus(string username, string password, string userType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetLoginStatus", ReplyAction="http://tempuri.org/IService1/GetLoginStatusResponse")]
        System.Threading.Tasks.Task<bool> GetLoginStatusAsync(string username, string password, string userType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/BorrowBook", ReplyAction="http://tempuri.org/IService1/BorrowBookResponse")]
        bool BorrowBook(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/BorrowBook", ReplyAction="http://tempuri.org/IService1/BorrowBookResponse")]
        System.Threading.Tasks.Task<bool> BorrowBookAsync(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ReturnBook", ReplyAction="http://tempuri.org/IService1/ReturnBookResponse")]
        bool ReturnBook(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ReturnBook", ReplyAction="http://tempuri.org/IService1/ReturnBookResponse")]
        System.Threading.Tasks.Task<bool> ReturnBookAsync(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SendEmail", ReplyAction="http://tempuri.org/IService1/SendEmailResponse")]
        bool SendEmail(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SendEmail", ReplyAction="http://tempuri.org/IService1/SendEmailResponse")]
        System.Threading.Tasks.Task<bool> SendEmailAsync(string username);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : ClientApplication.ServiceReference4.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<ClientApplication.ServiceReference4.IService1>, ClientApplication.ServiceReference4.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetData(int value) {
            return base.Channel.GetData(value);
        }
        
        public System.Threading.Tasks.Task<string> GetDataAsync(int value) {
            return base.Channel.GetDataAsync(value);
        }
        
        public RetailApplication.CompositeType GetDataUsingDataContract(RetailApplication.CompositeType composite) {
            return base.Channel.GetDataUsingDataContract(composite);
        }
        
        public System.Threading.Tasks.Task<RetailApplication.CompositeType> GetDataUsingDataContractAsync(RetailApplication.CompositeType composite) {
            return base.Channel.GetDataUsingDataContractAsync(composite);
        }
        
        public RetailApplication.Books[] GetBookByTitle(string value) {
            return base.Channel.GetBookByTitle(value);
        }
        
        public System.Threading.Tasks.Task<RetailApplication.Books[]> GetBookByTitleAsync(string value) {
            return base.Channel.GetBookByTitleAsync(value);
        }
        
        public RetailApplication.Books[] GetBookByAuthor(string value) {
            return base.Channel.GetBookByAuthor(value);
        }
        
        public System.Threading.Tasks.Task<RetailApplication.Books[]> GetBookByAuthorAsync(string value) {
            return base.Channel.GetBookByAuthorAsync(value);
        }
        
        public RetailApplication.Books[] GetBookByKeyword(string value) {
            return base.Channel.GetBookByKeyword(value);
        }
        
        public System.Threading.Tasks.Task<RetailApplication.Books[]> GetBookByKeywordAsync(string value) {
            return base.Channel.GetBookByKeywordAsync(value);
        }
        
        public bool AddBook(int id, string bookTitle, string bookAuthor, string publication, int year, string code, string bookKeyword) {
            return base.Channel.AddBook(id, bookTitle, bookAuthor, publication, year, code, bookKeyword);
        }
        
        public System.Threading.Tasks.Task<bool> AddBookAsync(int id, string bookTitle, string bookAuthor, string publication, int year, string code, string bookKeyword) {
            return base.Channel.AddBookAsync(id, bookTitle, bookAuthor, publication, year, code, bookKeyword);
        }
        
        public bool DeleteBook(int id) {
            return base.Channel.DeleteBook(id);
        }
        
        public System.Threading.Tasks.Task<bool> DeleteBookAsync(int id) {
            return base.Channel.DeleteBookAsync(id);
        }
        
        public bool GetLoginStatus(string username, string password, string userType) {
            return base.Channel.GetLoginStatus(username, password, userType);
        }
        
        public System.Threading.Tasks.Task<bool> GetLoginStatusAsync(string username, string password, string userType) {
            return base.Channel.GetLoginStatusAsync(username, password, userType);
        }
        
        public bool BorrowBook(string username) {
            return base.Channel.BorrowBook(username);
        }
        
        public System.Threading.Tasks.Task<bool> BorrowBookAsync(string username) {
            return base.Channel.BorrowBookAsync(username);
        }
        
        public bool ReturnBook(string username) {
            return base.Channel.ReturnBook(username);
        }
        
        public System.Threading.Tasks.Task<bool> ReturnBookAsync(string username) {
            return base.Channel.ReturnBookAsync(username);
        }
        
        public bool SendEmail(string username) {
            return base.Channel.SendEmail(username);
        }
        
        public System.Threading.Tasks.Task<bool> SendEmailAsync(string username) {
            return base.Channel.SendEmailAsync(username);
        }
    }
}
